Changes beta values to winterRun values.
CVPIA-OSC/winterRunDSM pull request #3
Opened 2021-02-15 23:31 UTC by ErinCain

-TODO still need to review betas and may want to simplify some functions now that betas are simpler

I made a first attempt at the betas and wanted to review the rest with you.

2021-02-16 17:43 UTC, ErinCain commented
What are the differences between the `prop diversions`, `proportion diversion`, and `percent diversions` in the betas in the survival functions. They seem like they should all be the same...also some are scaled and some are not.

2021-02-17 17:42 UTC, ergz commented on R/ocean_entry_success.R
> +                                          `intercept 31` = -2.9839253, months = 0.35)){
can you add the name of the watershed for these intercepts

2021-02-17 17:44 UTC, ergz requested changes
update names of the intercepts

2021-02-17 17:51 UTC, ergz approved these changes

2021-02-17 17:51 UTC, merged